{% set name = "bibtools" %}
{% set version = "0.3" %}
{% set md5 = "3b4cdd255d58db4b733a8587a6f34e79" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - bib = bibtools.cli:commandline
  number: 0

requirements:
  build:
    - pwkit
    - python
    - setuptools
    - six

  run:
    - pwkit
    - python
    - six

about:
  home: https://github.com/pkgw/bibtools/
  license: MIT License
  summary: A command-line bibliography manager.
